# Generated by Django 4.1.7 on 2023-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('sub', models.CharField(max_length=200)),
                ('first', models.TextField()),
                ('second', models.TextField(blank=True)),
                ('third', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('simage', models.ImageField(blank=True, upload_to='')),
                ('timage', models.ImageField(blank=True, upload_to='')),
                ('date', models.DateField()),
                ('bibliography', models.CharField(max_length=250)),
            ],
        ),
    ]
