# Generated by Django 4.1.7 on 2023-06-10 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('sub', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('sub', models.CharField(default='*', max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('first', models.TextField()),
                ('second', models.TextField(blank=True)),
                ('third', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('simage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('timage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date', models.DateField()),
                ('bibliography', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=200, null=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.topics')),
            ],
        ),
    ]
