# Generated by Django 4.1.7 on 2023-06-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='slug',
        ),
    ]
