# Generated by Django 4.1.7 on 2023-06-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_topics_post_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sub',
            new_name='year',
        ),
    ]
