# Generated by Django 4.1.7 on 2023-06-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_sub_post_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub',
            field=models.CharField(default='*', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
