# Generated by Django 4.1.7 on 2023-06-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_sub_alter_post_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
